### ISSUE TITLE
getting blury screen after integration with flutter app

### ISSUE THREAD

**Issue by shihab-cheq** [robodigital/cobrowseio_flutter#1]
Dear robo digital,
thanks for your awesome plugins for flutter. I integrated with following code in my project. I got promoted with permission as well & I accepted and got details in **cobrowse.io** dashboard. But I shows blurry screen most of the time in my free session. I don't know the reasons. Do you have the idea how to fix this issue? 

`String result = await CobrowseIO.start("*******", {
    'custom_data_field': 'Test'
  });`
  
  I attached below image link for clarification. 

[Photo Link](https://imgur.com/a/LB5hjOC)

**Comment by robinbonnes** [comment]
Hey @shihab-cheq,

Thanks for using our flutter plugin. I think this is related to the Cobrowse.io native SDK in relation to your device type.
The best option is to contact the Cobrowse.io team.

**Comment by shihab-cheq** [comment]
Thanks again for quick reply. I was trying in emulator. I will run on real device and let you know soon.

**Comment by shihab-cheq** [comment]
It works fine after purchasing paid version. So, no issue for paid version user. I am closing ticket.
