### ISSUE TITLE
[Android] Hand Control Scrolling not working on Flutter 2.8.1

### ISSUE THREAD

**Issue by chengboonrong** [robodigital/cobrowseio_flutter#11]
This is not happening until I upgraded Flutter framework version of my project from 2.2.1 to 2.8.1.
FYI, it happened on android devices, with Cobrowse SDK version 2.19.0 and I have tried updating the Cobrowse SDK version to the latest which is currently 2.23.0 but no luck. 

I have tried to reach out to the Cobrowse Support team and they think the issue could be the flutter framework upgrade. Since they are not officially support for flutter app, so they actually mentioned that I can report the issue here.

Please advise. Thanks!

You can refer to the demo video [here](https://drive.google.com/file/d/14-ir8Y6DorOaaaRwQ5ffa653DgoCbkZq/view?usp=sharing).

**Comment by chengboonrong** [comment]
FYI, this issue only happened in Flutter UI, meaning that native UI from Java activity was totally working fine.

**Comment by chengboonrong** [comment]
@robinbonnes

**Comment by robinbonnes** [comment]
Hello @chengboonrong,

I'm on the latest Flutter stable version (3.3.4) and here it is working for a normal listview menu:

```
 @override
  Widget build(BuildContext context) {
    return Drawer(
      child: ListView(
        children: <Widget>[]
      ),
    );
  }
```

Maybe its due to any custom scroll gesture?

**Comment by chengboonrong** [comment]
Hi @robinbonnes , it seems to be working on Flutter version 3.0.0 onwards again. Thanks for the update here!
