### ISSUE TITLE
Strange Results when screen sharing

### ISSUE THREAD

**Issue by BJRichardsAZ** [robodigital/cobrowseio_flutter#2]
We are currently making use of the plug in our app and are able to generate screen share requests, provide data to the Cobrowse dashboard, and connect users to a session. However, on any phone that isn't a samsung model we seem to be getting odd screen results. On IOS we are seeing a wierd zoom in effect occurring but only on certain elements  of the app: 
![Screen Shot 2022-02-04 at 11 57 51 AM](https://user-images.githubusercontent.com/72472725/152609366-cbef96d6-8a55-4e23-a094-8b9d30f34332.png)
and on a google pixel we are getting some strange kind of screen artifact, sometimes its flat colors, sometimes we can see a glimpse of the app ui.
![Screen Shot 2022-02-04 at 11 56 35 AM](https://user-images.githubusercontent.com/72472725/152609446-be89fc18-1c77-498d-8455-f5a4bacdf830.png)

**Comment by HGray384** [comment]
Hi Robo Digital, it's Harry from Cobrowse.io. I let our Flutter users know about your plug in when they come our way! Thanks for making it open to the community. 

In an email conversation to @BJRichardsAZ, I've suggested our [alternative render method for iOS](https://docs.cobrowse.io/sdk-features/advanced-features/ios/alternate-render-method) which should hopefully fix the iOS problems. 

Do you have any insight on the Android issue above? This isn't something we've seen before. Is there any more info you might need from @BJRichardsAZ?

**Comment by robinbonnes** [comment]
@BJRichardsAZ Thanks for using our plugin. We are using the plugin ourselves for a while and don't have any issues so far. For iOS indeed try using the alternative render method by adding this To your info.plist dict:

```
	<key>CBIORenderMethod</key>
	<integer>2</integer>
```

We also use the alternative render method. For Android I think this is related to the Cobrowse SDK. As this plugin just enables the SDK for Flutter. For now you can use the full device option at the bottom of the screen.

@HGray384 Thanks for pointing Flutter users to our plugin. Maybe you can discuss with your team if the alternative render method for iOS can be the default or make it a SDK option, so we can make this for Flutter the default. Also if you have a Google Pixel device available, can you try to test if it is working with the Cobrowse SDK? In this way we know if it is related to the SDK or our plugin.
