### ISSUE TITLE
Using 6 digit codes to identify devices

### ISSUE THREAD

**Issue by BJRichardsAZ** [robodigital/cobrowseio_flutter#3]
We would like to use 6 digit codes in our app to identify user devices so we can connect and help users who haven't fully set up accounts yet. Right now all it seems we can do is set up a user account and pass information from the user's account details to the plug in so that we can identify devices in the cobrowse dashboard. Are there any properties in the package right now for accessing the 6 digit codes generated for a device? We would like to display the identifying code to the user so they can pass it along to a support agent.

**Comment by robinbonnes** [comment]
Thanks for the feedback. 

I've just implemented the 6-digit code functionally. Update this package to versions `1.0.1` in your pubspec.yaml file and then call: `String code = await CobrowseIO.getCode()` after init. 

See the readme and example for more details.

Note: You have to create your own UI logic for displaying the 6-digit code to the user.

**Comment by BJRichardsAZ** [comment]
Thanks so much!
