### ISSUE TITLE
Full Device Remote Control (android)

### ISSUE THREAD

**Issue by BJRichardsAZ** [robodigital/cobrowseio_flutter#5]
Would it be possible to invoke the methods from this page https://docs.cobrowse.io/sdk-features/full-device-capabilities/full-device-remote-control in the documentation to see if user's have enabled the accessibility service need for full remote control of the device? We would also like to be able to rout them to the settings page mentioned here in a similar way.

**Comment by BJRichardsAZ** [comment]
I've been trying to see if I can implement this on our side using a fork of your repository but I'm having a bit of trouble. Let me know if you might have any insights!

**Comment by robinbonnes** [comment]
Thanks for the suggestion. I've just implemented it in the new version.

Do you want to test this out by changing under `dependencies` in your pubspec.yaml to:

```
  cobrowseio_flutter:
    git:
      url: https://github.com/robodigital/cobrowseio_flutter
```

See the readme for install instructions.

**Comment by BJRichardsAZ** [comment]
This seems to be working great! Thanks for such quick response.
