### ISSUE TITLE
iOS doesn't give me the code

### ISSUE THREAD

**Issue by amedeopro** [robodigital/cobrowseio_flutter#8]
When I click on the button that should return the code nothing happens, while on android it works regularly, the strange thing is that the iOS device for which I do not have the code I find it among the devices available in my Cobrowse.io dashboard, I'm using the free license for the moment to do some tests. How can I solve? A thousand thanks

**Comment by robinbonnes** [comment]
When you call `CobrowseIO.start()`, your device should be available in the list. When you call `CobrowseIO.getCode()` it should generate a unique code so you can identify the device directly. I can confirm it does work here on an iPhone 6S (iOS 15.4.1).

**Comment by amedeopro** [comment]
i use this function and getCode() work only on Android 

```dart
  String helpCode = '';

  Future getAssistence() async{
    await CobrowseIO.start("xxxxxxxx", {
      'device': 'Test from iOS'
    });
    print(await CobrowseIO.getCode());
    setState(() async {
      helpCode = await CobrowseIO.getCode();
    });
    if (Platform.isAndroid) {

      // Or: Check if we have access to full remote control.
      if (!await CobrowseIO.accessibilityServiceIsRunning()) {

        // If not, open the accesibility service settings to let the user give access.
        CobrowseIO.accessibilityServiceOpenSettings();
      }

      // Or: Show the default setup screen.
      CobrowseIO.accessibilityServiceShowSetup();
    }

}
```

**Comment by robinbonnes** [comment]
Do you see any errors in your xCode console?

**Comment by amedeopro** [comment]
I have no errors in the console

**Comment by amedeopro** [comment]
i have tried to print the code in console but work only with android

**Comment by khang-dev** [comment]
@amedeopro try to remove the await of this call
await CobrowseIO.start

**Comment by amedeopro** [comment]
@khang-dev i have the same result

**Comment by amedeopro** [comment]
can i test in another way? @khang-dev @robinbonnes thank you

**Comment by amedeopro** [comment]
I also tried on the fiscal device but nothing to do, always the same result

**Comment by amedeopro** [comment]
Is there someone who can help me?

**Comment by robinbonnes** [comment]
@amedeopro I use it this way:

```
String supportCode = "";

initState() {
    super.initState();

    CobrowseIO.start('licensekey', {});
    CobrowseIO.getCode().then((code) {
      setState(() {
        supportCode = code;
      });
    });
}
```

This does work for me for an iPhone 6S (iOS 15.4.1). However if this doesn't work for you, you can always fork and clone this plugin, change your pubspec to:

```
dependencies:
  cobrowseio_flutter:
    path: localpath/where/you/did/clone/the/plugin
```

Then in the file `localpath/where/you/did/clone/the/plugin/ios/Classes/CobrowseIOFlutterPlugin.m` in the `getCode` function put some debugging log lines like:

```
NSLog(@"Code does run");
NSLog(@"%@", session.code);
```

And check in your xCode console if the code runs and if it does display a code.

**Comment by amedeopro** [comment]
thank you so much, now it work. @robinbonnes
